name: Build WAR (Ant)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Prepare tools (CopyLibs + Jakarta Servlet API)
        run: |
          mkdir -p tools
          curl -L -o tools/jakarta.servlet-api-6.0.0.jar https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/6.0.0/jakarta.servlet-api-6.0.0.jar
          curl -L -o tools/org-netbeans-modules-java-j2seproject-copylibstask-RELEASE110.jar https://repo1.maven.org/maven2/org/netbeans/external/org-netbeans-modules-java-j2seproject-copylibstask/RELEASE110/org-netbeans-modules-java-j2seproject-copylibstask-RELEASE110.jar

      - name: Build with Ant (clean dist)
        run: |
          ant -version
          ant -Dlibs.CopyLibs.classpath="$(pwd)/tools/org-netbeans-modules-java-j2seproject-copylibstask-RELEASE110.jar" \
              -Dj2ee.platform.classpath="$(pwd)/tools/jakarta.servlet-api-6.0.0.jar" \
              -Dfile.reference.angus-mail-2.0.3.jar="lib/angus-mail-2.0.3.jar" \
              -Dfile.reference.jakarta.activation-2.0.1.jar="lib/jakarta.activation-2.0.1.jar" \
              -Dfile.reference.jakarta.mail-api-2.1.3.jar="lib/jakarta.mail-api-2.1.3.jar" \
              -Dfile.reference.mysql-connector-j-9.4.0.jar="lib/mysql-connector-j-9.4.0/mysql-connector-j-9.4.0.jar" \
              clean dist

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pahana_BookStore-war
          path: dist/Pahana_BookStore.war
